/*
 * CMake autogenerated config.h file.
 * Make changes to config.h.cmake instead of this file.
 */

/***************************************************************************
 * Copyright (C) 2011 by Robert G. Jakabosky <bobby@sharedrealm.com>       *
 *                                                                         *
 ***************************************************************************/

#ifndef __LLNET_CONFIG_H__
#define __LLNET_CONFIG_H__

/* system headers */
#cmakedefine HAVE_SYS_EVENTFD_H
#cmakedefine HAVE_SYS_SIGNALFD_H
#cmakedefine HAVE_SYS_TIMERFD_H

/* system features */
#cmakedefine HAVE_getservbyname_r
#cmakedefine HAVE_getservbyport_r
#cmakedefine HAVE_getprotobyname_r
#cmakedefine HAVE_getprotobynumber_r
#cmakedefine HAVE_IPV6

#endif /* __LLNET_CONFIG_H__ */
